### PR TITLE
Migrate the test csp and usage data hooks

### PR DESCRIPTION
**Pull request by smarlowucf**
From the core package to test plugin.

### CODE REVIEW

**Comment by smarlowucf** [comment]
This looks like a lot but it's all migrated code. This is from the local csp and product api test plugins in core package. Splitting these out to allow for easy composition of test deployments.

**Comment by smarlowucf** [comment]
Note: all the repo setup I copied directly from the Amazon plugin and only changed names s/amazon/test so I pushed that direct to main.

**Review by KeithMnemonic — APPROVED** [review]
LGTM

**Comment by smarlowucf** [comment]
Going ahead with merge to get this in the test container. Feel free to still add comments that can be resolved in a separate pr.

**Pull request merged**
